#Les ports relies le port de la machine hôte vers le port du conatainer.

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_rh_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-rh_predictions_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rh_predictions_db"]
      interval: 5s
      timeout: 5s
      retries: 10

#Script d'insertion du contenue de Data/X.csv et Data/y.csv dans la base de données.
#volumes pour la lecture des .csv dans le projet backend.
  db-init-csv:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: db_init_csv
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-rh_predictions_db}
      DATA_DIR: /app/Data
    volumes:
      - ./Data:/app/Data:ro
    command: ["python", "script/insert_X_and_y_tables.py"]

# Le ou les modèles skit-learn sont montés dans un volume pour ne pas builder l'API en l'incluant.
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      postgres:
        condition: service_healthy
      db-init-csv:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-rh_predictions_db}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/modeles:/app/modeles

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: p5_frontend
    depends_on:
      - api
    ports:
      - "8080:80"
#Volume pour le stockage persistant des données de la base de données PostgreSQL.
volumes:
  pgdata:
