---
- name: Update P5_predictions production
  hosts: production
  become: true

  vars_files:
    - vault.yml

  vars:
    app_dir: /app/P5_predictions
    ci_registry_image: ghcr.io/aurelien77/p5-deployez-un-modele-de-machine-learning

  tasks:
    - name: Copier docker-compose.prod.yml
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../docker-compose.prod.yml"
        dest: "{{ app_dir }}/devops/docker-compose.prod.yml"
        mode: "0644"

    - name: Régénérer .env.prod
      ansible.builtin.template:
        src: templates/env.prod.j2
        dest: "{{ app_dir }}/devops/.env.prod"
        mode: "0600"

    - name: Login GitHub Container Registry
      ansible.builtin.shell: |
        echo "{{ registry_token }}" | docker login ghcr.io -u "{{ registry_user }}" --password-stdin
      no_log: true

    - name: Mettre à jour la stack
      ansible.builtin.shell: |
        docker compose \
          --env-file devops/.env.prod \
          -f devops/docker-compose.prod.yml \
          up -d --pull always --remove-orphans
      args:
        chdir: "{{ app_dir }}"
      environment:
        CI_REGISTRY_IMAGE: "{{ ci_registry_image }}"
